# Generated by Django 4.2.3 on 2023-07-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.CharField()),
                ('photo_url', models.CharField()),
                ('google_id', models.CharField()),
                ('balance', models.IntegerField(default=0)),
                ('group', models.CharField(blank=True, choices=[('arts', 'Arts'), ('science', 'Science'), ('commerce', 'Commerce')], max_length=20, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
