# Generated by Django 4.2.3 on 2023-07-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo_url',
            field=models.CharField(),
        ),
    ]
