# Generated by Django 4.2.3 on 2023-07-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_time_exam_duration_remove_exam_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='name',
        ),
    ]
