# Generated by Django 4.2.3 on 2023-07-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_exam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='chapters',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subjects',
            field=models.CharField(max_length=1023),
        ),
    ]
