# Generated by Django 4.2.3 on 2023-07-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_exam_chapters_alter_exam_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='chapters',
            new_name='syllabus',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subjects',
        ),
    ]
