# Generated by Django 4.2.3 on 2023-07-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_rename_chapters_exam_syllabus_remove_exam_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='date',
            new_name='exam_date',
        ),
    ]
