# Generated by Django 4.2.3 on 2023-07-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_rename_date_exam_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateTimeField(),
        ),
    ]
