# Generated by Django 4.2.3 on 2023-07-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_exam_exam_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='package',
            new_name='course_package',
        ),
    ]
