# Generated by Django 4.2.3 on 2023-07-20 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_rename_package_exam_course_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='course_package',
            new_name='package',
        ),
    ]
