import { Component } from '@angular/core';
import {MCQType} from "./mcq.model";
@Component({
  selector: 'app-mcq',
  templateUrl: './mcq.component.html',
  styleUrls: ['./mcq.component.css'],
})
export class McqComponent {
  displayedColumns: string[] = ['id','question', 'subject', 'chapter', 'published'];
  dataSource = mcqList;
}


const mcqList: MCQType[] = [
  {
    id: 1,
    question: "What is the capital of France?",
    questionImg: null,
    optionText1: "Paris",
    optionImg1: null,
    optionText2: "London",
    optionImg2: null,
    optionText3: "Berlin",
    optionImg3: null,
    optionText4: "Madrid",
    optionImg4: null,
    optionText5: "Rome",
    optionImg5: null,
    correctAns: [1],
    explanation: "Paris is the capital of France.",
    explanationImg: null,
    multiChose: false,
    subject: 1,
    chapter: 2,
    hardness: 3,
    category: 4,
    point: 1,
    published: true,
  },
  {
    id: 2,
    question: "Who painted the Mona Lisa?",
    questionImg: null,
    optionText1: "Leonardo da Vinci",
    optionImg1: null,
    optionText2: "Pablo Picasso",
    optionImg2: null,
    optionText3: "Vincent van Gogh",
    optionImg3: null,
    optionText4: "Michelangelo",
    optionImg4: null,
    optionText5: "Salvador Dali",
    optionImg5: null,
    correctAns: [1],
    explanation: "Leonardo da Vinci painted the Mona Lisa.",
    explanationImg: null,
    multiChose: false,
    subject: 1,
    chapter: 2,
    hardness: 3,
    category: 4,
    point: 1,
    published: true,
  },
  {
    id: 3,
    question: "What is the largest planet in our solar system?",
    questionImg: null,
    optionText1: "Jupiter",
    optionImg1: null,
    optionText2: "Saturn",
    optionImg2: null,
    optionText3: "Mars",
    optionImg3: null,
    optionText4: "Earth",
    optionImg4: null,
    optionText5: "Neptune",
    optionImg5: null,
    correctAns: [1],
    explanation: "Jupiter is the largest planet in our solar system.",
    explanationImg: null,
    multiChose: false,
    subject: 1,
    chapter: 2,
    hardness: 3,
    category: 4,
    point: 1,
    published: true,
  },
  {
    id: 4,
    question: "Who wrote the play 'Romeo and Juliet'?",
    questionImg: null,
    optionText1: "William Shakespeare",
    optionImg1: null,
    optionText2: "Jane Austen",
    optionImg2: null,
    optionText3: "Charles Dickens",
    optionImg3: null,
    optionText4: "Mark Twain",
    optionImg4: null,
    optionText5: "Harper Lee",
    optionImg5: null,
    correctAns: [1],
    explanation: "William Shakespeare wrote the play 'Romeo and Juliet'.",
    explanationImg: null,
    multiChose: false,
    subject: 1,
    chapter: 2,
    hardness: 3,
    category: 4,
    point: 1,
    published: true,
  },
  {
    id: 5,
    question: "Which is the largest ocean on Earth?",
    questionImg: null,
    optionText1: "Pacific Ocean",
    optionImg1: null,
    optionText2: "Atlantic Ocean",
    optionImg2: null,
    optionText3: "Indian Ocean",
    optionImg3: null,
    optionText4: "Arctic Ocean",
    optionImg4: null,
    optionText5: "Southern Ocean",
    optionImg5: null,
    correctAns: [1],
    explanation: "The Pacific Ocean is the largest ocean on Earth.",
    explanationImg: null,
    multiChose: false,
    subject: 1,
    chapter: 2,
    hardness: 3,
    category: 4,
    point: 1,
    published: true,
  },
  {
    id: 6,
    question: "What is the chemical symbol for gold?",
    questionImg: null,
    optionText1: "Au",
    optionImg1: null,
    optionText2: "Ag",
    optionImg2: null,
    optionText3: "Fe",
    optionImg3: null,
    optionText4: "Cu",
    optionImg4: null,
    optionText5: "Pb",
    optionImg5: null,
    correctAns: [1],
    explanation: "The chemical symbol for gold is Au.",
    explanationImg: null,
    multiChose: false,
    subject: 1,
    chapter: 2,
    hardness: 3,
    category: 4,
    point: 1,
    published: true,
  },
  {
    id: 7,
    question: "What year did the Titanic sink?",
    questionImg: null,
    optionText1: "1912",
    optionImg1: null,
    optionText2: "1905",
    optionImg2: null,
    optionText3: "1923",
    optionImg3: null,
    optionText4: "1931",
    optionImg4: null,
    optionText5: "1945",
    optionImg5: null,
    correctAns: [1],
    explanation: "The Titanic sank in the year 1912.",
    explanationImg: null,
    multiChose: false,
    subject: 1,
    chapter: 2,
    hardness: 3,
    category: 4,
    point: 1,
    published: true,
  },
  {
    id: 8,
    question: "What is the largest organ in the human body?",
    questionImg: null,
    optionText1: "Skin",
    optionImg1: null,
    optionText2: "Heart",
    optionImg2: null,
    optionText3: "Liver",
    optionImg3: null,
    optionText4: "Brain",
    optionImg4: null,
    optionText5: "Lung",
    optionImg5: null,
    correctAns: [1],
    explanation: "The largest organ in the human body is the skin.",
    explanationImg: null,
    multiChose: false,
    subject: 1,
    chapter: 2,
    hardness: 3,
    category: 4,
    point: 1,
    published: true,
  },
  {
    id: 9,
    question: "Which country is known as the 'Land of the Rising Sun'?",
    questionImg: null,
    optionText1: "Japan",
    optionImg1: null,
    optionText2: "China",
    optionImg2: null,
    optionText3: "India",
    optionImg3: null,
    optionText4: "South Korea",
    optionImg4: null,
    optionText5: "Thailand",
    optionImg5: null,
    correctAns: [1],
    explanation: "Japan is known as the 'Land of the Rising Sun'.",
    explanationImg: null,
    multiChose: false,
    subject: 1,
    chapter: 2,
    hardness: 3,
    category: 4,
    point: 1,
    published: true,
  },
  {
    id: 10,
    question: "Which planet is known as the 'Red Planet'?",
    questionImg: null,
    optionText1: "Mars",
    optionImg1: null,
    optionText2: "Mercury",
    optionImg2: null,
    optionText3: "Venus",
    optionImg3: null,
    optionText4: "Jupiter",
    optionImg4: null,
    optionText5: "Saturn",
    optionImg5: null,
    correctAns: [1],
    explanation: "Mars is known as the 'Red Planet'.",
    explanationImg: null,
    multiChose: false,
    subject: 1,
    chapter: 2,
    hardness: 3,
    category: 4,
    point: 1,
    published: true,
  },
  {
    id: 11,
    question: "What is the largest species of shark?",
    questionImg: null,
    optionText1: "Whale Shark",
    optionImg1: null,
    optionText2: "Great White Shark",
    optionImg2: null,
    optionText3: "Tiger Shark",
    optionImg3: null,
    optionText4: "Hammerhead Shark",
    optionImg4: null,
    optionText5: "Basking Shark",
    optionImg5: null,
    correctAns: [1],
    explanation: "The Whale Shark is the largest species of shark.",
    explanationImg: null,
    multiChose: false,
    subject: 1,
    chapter: 2,
    hardness: 3,
    category: 4,
    point: 1,
    published: true,
  },
  {
    id: 12,
    question: "Who is the author of the Harry Potter book series?",
    questionImg: null,
    optionText1: "J.K. Rowling",
    optionImg1: null,
    optionText2: "Stephen King",
    optionImg2: null,
    optionText3: "George R.R. Martin",
    optionImg3: null,
    optionText4: "J.R.R. Tolkien",
    optionImg4: null,
    optionText5: "Suzanne Collins",
    optionImg5: null,
    correctAns: [1],
    explanation: "J.K. Rowling is the author of the Harry Potter book series.",
    explanationImg: null,
    multiChose: false,
    subject: 1,
    chapter: 2,
    hardness: 3,
    category: 4,
    point: 1,
    published: true,
  },
  {
    id: 13,
    question: "What is the currency of Brazil?",
    questionImg: null,
    optionText1: "Real",
    optionImg1: null,
    optionText2: "Peso",
    optionImg2: null,
    optionText3: "Euro",
    optionImg3: null,
    optionText4: "Yen",
    optionImg4: null,
    optionText5: "Dollar",
    optionImg5: null,
    correctAns: [1],
    explanation: "The currency of Brazil is the Real.",
    explanationImg: null,
    multiChose: false,
    subject: 1,
    chapter: 2,
    hardness: 3,
    category: 4,
    point: 1,
    published: true,
  },
  {
    id: 14,
    question: "What is the tallest mountain in the world?",
    questionImg: null,
    optionText1: "Mount Everest",
    optionImg1: null,
    optionText2: "K2",
    optionImg2: null,
    optionText3: "Kangchenjunga",
    optionImg3: null,
    optionText4: "Lhotse",
    optionImg4: null,
    optionText5: "Makalu",
    optionImg5: null,
    correctAns: [1],
    explanation: "Mount Everest is the tallest mountain in the world.",
    explanationImg: null,
    multiChose: false,
    subject: 1,
    chapter: 2,
    hardness: 3,
    category: 4,
    point: 1,
    published: true,
  },
  {
    id: 15,
    question: "Who is the current President of the United States?",
    questionImg: null,
    optionText1: "Joe Biden",
    optionImg1: null,
    optionText2: "Barack Obama",
    optionImg2: null,
    optionText3: "Donald Trump",
    optionImg3: null,
    optionText4: "George Washington",
    optionImg4: null,
    optionText5: "Abraham Lincoln",
    optionImg5: null,
    correctAns: [1],
    explanation: "Joe Biden is the current President of the United States.",
    explanationImg: null,
    multiChose: false,
    subject: 1,
    chapter: 2,
    hardness: 3,
    category: 4,
    point: 1,
    published: true,
  },
// Add more objects here...
];
