# Generated by Django 4.2.3 on 2023-07-31 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mcq', '0001_initial'),
        ('exam', '0002_alter_exam_exam_date'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('penalty', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.exam')),
            ],
        ),
        migrations.CreateModel(
            name='MCQSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_option', models.CharField(max_length=1)),
                ('exam_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_submittion.examsubmission')),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.mcq')),
            ],
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='mcq_list',
            field=models.ManyToManyField(through='exam_submittion.MCQSubmission', to='mcq.mcq'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student'),
        ),
    ]
