# Generated by Django 4.2.3 on 2023-08-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_submittion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubmission',
            name='penalty',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='point',
            field=models.IntegerField(null=True),
        ),
    ]
