# Generated by Django 4.2.3 on 2023-08-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_submittion', '0002_alter_examsubmission_penalty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubmission',
            name='penalty',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='point',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
