# Generated by Django 4.2.3 on 2023-08-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_submittion', '0003_alter_examsubmission_penalty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqsubmission',
            name='submitted_option',
            field=models.IntegerField(),
        ),
    ]
