# Generated by Django 4.2.3 on 2023-07-09 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_img_url', models.ImageField(blank=True, null=True, upload_to='mcq')),
                ('option_text_1', models.CharField(max_length=100)),
                ('option_img_url_1', models.ImageField(blank=True, null=True, upload_to='mcq')),
                ('option_text_2', models.CharField(max_length=100)),
                ('option_img_url_2', models.ImageField(blank=True, null=True, upload_to='mcq')),
                ('option_text_3', models.CharField(max_length=100)),
                ('option_img_url_3', models.ImageField(blank=True, null=True, upload_to='mcq')),
                ('option_text_4', models.CharField(max_length=100)),
                ('option_img_url_4', models.ImageField(blank=True, null=True, upload_to='mcq')),
                ('correct_ans', models.CharField(max_length=100)),
                ('explanation', models.TextField()),
                ('explanation_img', models.ImageField(blank=True, null=True, upload_to='mcq')),
                ('hardness', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('subject', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('problem_setter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
