# Generated by Django 4.2.3 on 2023-07-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
