# Generated by Django 4.2.3 on 2023-08-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='correct_ans',
            field=models.IntegerField(),
        ),
    ]
