# Generated by Django 4.2.3 on 2023-08-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_alter_package_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('varsity', 'Varsity'), ('medical', 'Medical'), ('engineering', 'Engineering'), ('free_exam', 'Free Exam'), ('hsc', 'Hsc'), ('guccho', 'Guccho')], max_length=20),
        ),
    ]
