# Generated by Django 4.2.3 on 2023-08-08 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionbank',
            old_name='university',
            new_name='varsity',
        ),
    ]
