# Generated by Django 4.2.3 on 2023-07-09 09:18

import custom_user.user_enum
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[(custom_user.user_enum.UserRoleEnum['admin'], 'Admin'), (custom_user.user_enum.UserRoleEnum['super_admin'], 'Super Admin'), (custom_user.user_enum.UserRoleEnum['problem_setter'], 'Problem Setter'), (custom_user.user_enum.UserRoleEnum['student'], 'Student')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
