# Generated by Django 4.2.3 on 2023-07-09 10:04

import custom_user.user_enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[(custom_user.user_enum.UserRoleEnum['admin'], 'Admin'), (custom_user.user_enum.UserRoleEnum['super_admin'], 'Super Admin'), (custom_user.user_enum.UserRoleEnum['problem_setter'], 'Problem Setter'), (custom_user.user_enum.UserRoleEnum['student'], 'Student')], default=custom_user.user_enum.UserRoleEnum['student'], max_length=50),
        ),
    ]
