# Generated by Django 4.2.3 on 2023-07-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_remove_customuser_is_stafff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_stafff',
            field=models.BooleanField(default=True),
        ),
    ]
