# Generated by Django 4.2.3 on 2023-07-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_customuser_is_stafff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_stafff',
        ),
    ]
