# Generated by Django 4.2.3 on 2023-07-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('super_admin', 'Super Admin'), ('problem_setter', 'Problem Setter'), ('student', 'Student')], default='Student', max_length=20),
        ),
    ]
